### ISSUE TITLE
*feature request* Colocar opcion para mostrar siempre los iconos de reply, retweet y los demas

### ISSUE THREAD

**Issue by chepe263** [rodrigopolo/EvenBetterTweetDeck#1]
Seria posible colocar una opcion en la configuracion de la extension para que se muestren siempre los iconos de las acciones reply, retweet y las otras?

Esto seria muy util en dispositivos con pantalla tactil.

**Comment by rodrigopolo** [comment]
Mmmm.. varios puntos a considerar.

1. Yo no hice el plug-in, sólo le agregué los nuevos íconos de Apple y remplacé la forma en la que TweetDeck.com carga esas madres.
2. sería de que le escribieras al dude del plug-in original.
3. No creo que sea visualmente funcional o cómodo tener todos los ingratos botones siempre visibles, pero sé que en gustos se rompen géneros.
